SET GLOBAL bigram_normalization=OFF;
SET GLOBAL bigram_unicode_version="DEFAULT";

DROP TABLE IF EXISTS bi;
CREATE TABLE bi (a TEXT, FULLTEXT(a) WITH PARSER bigram) CHARSET latin1;
INSERT INTO bi VALUES ("abcde");
INSERT INTO bi VALUES ("dummy");
INSERT INTO bi VALUES ("dummyde");
SELECT COUNT(*) FROM bi WHERE MATCH(a) AGAINST('abcde');
SELECT COUNT(*) FROM bi WHERE MATCH(a) AGAINST('bcd');
SELECT COUNT(*) FROM bi WHERE MATCH(a) AGAINST('ab' IN BOOLEAN MODE);
SELECT COUNT(*) FROM bi WHERE MATCH(a) AGAINST('+ab' IN BOOLEAN MODE);
SELECT COUNT(*) FROM bi WHERE MATCH(a) AGAINST('+de -du' IN BOOLEAN MODE);
SELECT COUNT(*) FROM bi WHERE MATCH(a) AGAINST('+abc' IN BOOLEAN MODE);
DROP TABLE IF EXISTS bi;

DROP TABLE IF EXISTS bi;
CREATE TABLE bi (a TEXT, FULLTEXT(a) WITH PARSER bigram) CHARSET utf8 COLLATE utf8_general_ci;
INSERT INTO bi VALUES ("ﾃｽﾄ");
SELECT COUNT(*) FROM bi WHERE MATCH(a) AGAINST('テスト' IN BOOLEAN MODE);
DROP TABLE IF EXISTS bi;

SET GLOBAL bigram_normalization="KD";
DROP TABLE IF EXISTS bi;
CREATE TABLE bi (a TEXT, FULLTEXT(a) WITH PARSER bigram) CHARSET utf8 COLLATE utf8_general_ci;
INSERT INTO bi VALUES ("ﾃｽﾄ");
SELECT COUNT(*) FROM bi WHERE MATCH(a) AGAINST('テスト' IN BOOLEAN MODE);
SELECT COUNT(*) FROM bi WHERE MATCH(a) AGAINST('デズド' IN BOOLEAN MODE);
DROP TABLE IF EXISTS bi;

SET GLOBAL bigram_normalization=OFF;
SET GLOBAL bigram_unicode_version="DEFAULT";
